name: Build

on:
  push:
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: |
        sudo apt-get update
        sudo apt-get install cmake ninja-build

    - name: Build & Test
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=MinSizeRel -DCMAKE_INSTALL_PREFIX=. -G Ninja .
        cmake --build build --target check k8pshd install/strip
        build/k8pshd --background --config=k8psh_example.conf --name=gcc --pidfile=k8psh.pid && sleep 1 && kill -9 $(cat k8psh.pid)

  docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Minikube
      uses: manusa/actions-setup-minikube@v2.7.0
      with:
        minikube version: 'v1.27.0'
        kubernetes version: 'v1.25.0'
        github token: ${{ secrets.GITHUB_TOKEN }}

    - name: Test Dockerfile
      run: |
        docker build . --tag 76eddge/k8psh --target deploy
        docker run -t --rm 76eddge/k8psh
        docker build . --tag 76eddge/k8psh:debug --target deploy-debug
        docker run -t --rm 76eddge/k8psh:debug
      env:
        DOCKER_BUILDKIT: 1

    - name: Create Asset
      run: |
        CONTAINER_ID=$(docker create 76eddge/k8psh)
        docker cp ${CONTAINER_ID}:/bin bin
        docker rm ${CONTAINER_ID}
        cd bin
        tar -czf ../k8psh-linux.tar.gz *

    - name: Test Asset
      run: |
        envsubst < test/k8s/test.yaml | kubectl apply -f -
        kubectl wait --for=condition=complete job/test || kubectl describe job/test
        kubectl logs job/test -c k8psh
        kubectl logs job/test -c server
        kubectl logs job/test -c client
        kubectl wait --for=condition=complete --timeout=0 job/test

    - name: Upload Asset
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: k8psh-linux.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup QEMU
      if: startsWith(github.ref, 'refs/tags/')
      uses: docker/setup-qemu-action@v2
      with:
        platforms: all

    - name: Create BuildKit Configuration
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        echo "[worker.oci]" > buildkitd.toml
        echo "max-parallelism=1" >> buildkitd.toml

    - name: Setup Docker Buildx
      if: startsWith(github.ref, 'refs/tags/')
      uses: docker/setup-buildx-action@v2
      with:
        version: latest
        config: buildkitd.toml

    - name: Login to DockerHub
      if: startsWith(github.ref, 'refs/tags/')
      run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username 76eddge --password-stdin

    - name: Push Docker Images
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        docker buildx build . --tag 76eddge/k8psh --tag 76eddge/k8psh:${GITHUB_REF/refs\/tags\//} --platform linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x --target deploy --push
        docker buildx build . --tag 76eddge/k8psh:debug --tag 76eddge/k8psh:${GITHUB_REF/refs\/tags\//}-debug --platform linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x --target deploy-debug --push

  windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - run: choco install cmake ninja

    - name: Enable MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Build & Test
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=MinSizeRel "-DCMAKE_INSTALL_PREFIX=." -G Ninja .
        cmake --build build --target check install

    - name: Create Asset
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        cd bin
        7z u -snh -mx9 ../k8psh-win.zip *

    - name: Upload Asset
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: k8psh-win.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - run: |
        brew update
        brew install cmake ninja

    - name: Build & Test
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=MinSizeRel -DCMAKE_INSTALL_PREFIX=. -G Ninja .
        cmake --build build --target check install/strip

    - name: Create Asset
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        cd bin
        tar -czf ../k8psh-mac.tar.gz *

    - name: Upload Asset
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: k8psh-mac.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
